import jsPDF from 'jspdf';

interface MetricDetail {
    name: string;
    value: number;
    description: string;
    status: string;
}

interface AnalysisResult {
    overall_score: number;
    verdict: string;
    details: MetricDetail[];
    sentences: any[];
}

export const generatePDF = (result: AnalysisResult) => {
    const doc = new jsPDF();

    // Brand Colors
    const primaryColor = '#0F172A'; // Slate 900
    const accentColor = result.overall_score > 50 ? '#E11D48' : '#10B981'; // Rose 600 or Emerald 500

    // Header Background
    doc.setFillColor(primaryColor);
    doc.rect(0, 0, 210, 40, 'F');

    // Header Text
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("VeritasAI", 20, 20);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Official Content Authenticity Report", 20, 30);

    doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 20);
    doc.text(`ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}`, 150, 26);

    // Score Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Analysis Result", 20, 60);

    // Score Circle visual approximation
    doc.setFontSize(40);
    doc.setTextColor(accentColor);
    doc.text(`${result.overall_score}%`, 20, 80);

    doc.setFontSize(24);
    doc.text(result.verdict, 60, 80);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const scoreText = result.overall_score > 50
        ? "This content shows strong patterns associated with AI generation."
        : "This content appears to be human-written with high confidence.";
    doc.text(scoreText, 20, 95);

    // Metrics Grid
    let yPos = 120;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("Detailed Metrics", 20, yPos);
    yPos += 10;

    result.details.forEach((metric, index) => {
        // Background for item
        if (index % 2 === 0) {
            doc.setFillColor(248, 250, 252);
            doc.rect(20, yPos, 170, 25, 'F');
        }

        doc.setFontSize(12);
        doc.setTextColor(50, 50, 50);
        doc.setFont("helvetica", "bold");
        doc.text(metric.name, 25, yPos + 10);

        doc.setFont("helvetica", "normal");
        doc.text(`${metric.value}`, 160, yPos + 10);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(metric.description, 25, yPos + 18);

        yPos += 25;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Report generated by VeritasAI. This is an automated assessment and should be used for informational purposes only.", 20, 280);

    doc.save("VeritasAI-Report.pdf");
};
